export const COFFEE_TYPES = [
  'ESPRESSO',
  'AMERICANO',
  'LATTE',
  'CAPPUCCINO',
  'FLAT_WHITE',
  'MACCHIATO',
  'MOCHA',
  'COLD_BREW',
  'ICED_COFFEE',
  'DRIP_COFFEE',
  'POUR_OVER',
  'FRENCH_PRESS',
  'OTHER',
] as const;

export type CoffeeType = typeof COFFEE_TYPES[number];

export const COFFEE_SIZES = ['SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE'] as const;

export type CoffeeSize = typeof COFFEE_SIZES[number];

// Caffeine content estimates in mg
export const CAFFEINE_CONTENT: Record<CoffeeType, Record<CoffeeSize, number>> = {
  ESPRESSO: { SMALL: 64, MEDIUM: 128, LARGE: 192, EXTRA_LARGE: 256 },
  AMERICANO: { SMALL: 77, MEDIUM: 154, LARGE: 231, EXTRA_LARGE: 308 },
  LATTE: { SMALL: 75, MEDIUM: 150, LARGE: 225, EXTRA_LARGE: 300 },
  CAPPUCCINO: { SMALL: 75, MEDIUM: 150, LARGE: 225, EXTRA_LARGE: 300 },
  FLAT_WHITE: { SMALL: 77, MEDIUM: 130, LARGE: 195, EXTRA_LARGE: 260 },
  MACCHIATO: { SMALL: 75, MEDIUM: 150, LARGE: 225, EXTRA_LARGE: 300 },
  MOCHA: { SMALL: 85, MEDIUM: 170, LARGE: 255, EXTRA_LARGE: 340 },
  COLD_BREW: { SMALL: 150, MEDIUM: 200, LARGE: 300, EXTRA_LARGE: 400 },
  ICED_COFFEE: { SMALL: 120, MEDIUM: 165, LARGE: 235, EXTRA_LARGE: 310 },
  DRIP_COFFEE: { SMALL: 95, MEDIUM: 140, LARGE: 210, EXTRA_LARGE: 280 },
  POUR_OVER: { SMALL: 95, MEDIUM: 145, LARGE: 218, EXTRA_LARGE: 290 },
  FRENCH_PRESS: { SMALL: 80, MEDIUM: 107, LARGE: 160, EXTRA_LARGE: 213 },
  OTHER: { SMALL: 80, MEDIUM: 120, LARGE: 180, EXTRA_LARGE: 240 },
};
